name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature or improvement you would like to see.
      placeholder: Describe your idea!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of atio are you running?
      options:
        - 2.1.0 (2025-08-14)
        - 2.0.0 (2025-08-13)
        - 1.0.0 (2025-08-02)
      default: 0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
